let homes = [
    {
        "id": 1,
        "name": "Natalie's Suit",
        "type": "apartment",
        "price": 50,
        "capacity": 4,
        "image": "pictures/home-1.jpg",
        "location": "Sofia",
        "booked": 10,
        "pets": true,
    },
    {
        "id": 2,
        "name": "Apartment Sofia View",
        "type": "apartment",
        "price": 30,
        "capacity": 2,
        "image": "pictures/home-2.jpg",
        "location": "Sofia",
        "booked": 56,
        "pets": true,
    },
    {
        "id": 3,
        "name": "Sea View Apartment",
        "type": "apartment",
        "price": 35,
        "capacity": 3,
        "image": "pictures/home-3.jpg",
        "location": "Varna",
        "booked": 80,
        "pets": true,
    },
    {
        "id": 4,
        "name": "City's Apartment",
        "type": "apartment",
        "price": 40,
        "capacity": 4,
        "image": "pictures/home-4.jpg",
        "location": "Varna",
        "booked": 34,
        "pets": false,
    },
    {
        "id": 5,
        "name": "Sky Home",
        "type": "apartment",
        "price": 67,
        "capacity": 4,
        "image": "pictures/home-5.jpg",
        "location": "Sofia",
        "booked": 97,
        "pets": true,
    },
    {
        "id": 6,
        "name": "Dreams Apartment",
        "type": "apartment",
        "price": 23,
        "capacity": 1,
        "image": "pictures/home-6.jpg",
        "location": "Sofia",
        "booked": 34,
        "pets": false,
    },
    {
        "id": 7,
        "name": "Roger's Design Apartment",
        "type": "apartment",
        "price": 90,
        "capacity": 3,
        "image": "pictures/home-7.jpg",
        "location": "Sofia",
        "booked": 95,
        "pets": false,
    },
    {
        "id": 8,
        "name": "Sunshine Apartment",
        "type": "apartment",
        "price": 90,
        "capacity": 3,
        "image": "pictures/home-8.jpg",
        "location": "Sofia",
        "booked": 123,
        "pets": false,
    },
    {
        "id": 9,
        "name": "Angela's suit",
        "type": "apartment",
        "price": 55,
        "capacity": 3,
        "image": "pictures/home-9.jpg",
        "location": "Sofia",
        "booked": 54,
        "pets": true,
    },
    {
        "id": 10,
        "name": "Nice Place",
        "type": "apartment",
        "price": 20,
        "capacity": 1,
        "image": "pictures/home-10.jpg",
        "location": "Sofia",
        "booked": 15,
        "pets": false,
    },
    {
        "id": 11,
        "name": "Elina's Place",
        "type": "apartment",
        "price": 45,
        "capacity": 3,
        "image": "pictures/home-11.jpg",
        "location": "Varna",
        "booked": 98,
        "pets": true,
    },
    {
        "id": 12,
        "name": "Smart Home",
        "type": "apartment",
        "price": 34,
        "capacity": 3,
        "image": "pictures/home-12.jpg",
        "location": "Varna",
        "booked": 10,
        "pets": false,
    },
    {
        "id": 13,
        "name": "Alexa's dream place",
        "type": "apartment",
        "price": 76,
        "capacity": 2,
        "image": "pictures/home-13.jpg",
        "location": "Varna",
        "booked": 34,
        "pets": true,
    },
    {
        "id": 14,
        "name": "Beach Sea View Apartment",
        "type": "apartment",
        "price": 65,
        "capacity": 4,
        "image": "pictures/home-14.jpg",
        "location": "Varna",
        "booked": 340,
        "pets": false,
    },
    {
        "id": 15,
        "name": "My Favorite Place",
        "type": "apartment",
        "price": 110,
        "capacity": 2,
        "image": "pictures/home-15.jpg",
        "location": "Varna",
        "booked": 23,
        "pets": false,
    },
    {
        "id": 16,
        "name": "Go Home Apartment",
        "type": "apartment",
        "price": 66,
        "capacity": 3,
        "image": "pictures/home-16.jpg",
        "location": "Sofia",
        "booked": 231,
        "pets": true,
    },
    {
        "id": 17,
        "name": "Party Zone Apartment",
        "type": "apartment",
        "price": 200,
        "capacity": 10,
        "image": "pictures/home-17.jpg",
        "location": "Sofia",
        "booked": 14,
        "pets": false,
    },
    {
        "id": 18,
        "name": "Green Stay",
        "type": "apartment",
        "price": 34,
        "capacity": 2,
        "image": "pictures/home-18.jpg",
        "location": "Varna",
        "booked": 879,
        "pets": true,
    },
    {
        "id": 19,
        "name": "Jana's Home",
        "type": "apartment",
        "price": 76,
        "capacity": 3,
        "image": "pictures/home-19.jpg",
        "location": "Sofia",
        "booked": 78,
        "pets": true,
    },
    {
        "id": 20,
        "name": "Group Home",
        "type": "apartment",
        "price": 155,
        "capacity": 8,
        "image": "pictures/home-20.jpg",
        "location": "Varna",
        "booked": 231,
        "pets": true,
    },
    {
        "id": 21,
        "name": "Vesta Home",
        "type": "apartment",
        "price": 76,
        "capacity": 4,
        "image": "pictures/home-21.jpg",
        "location": "Varna",
        "booked": 112,
        "pets": false,
    },
    {
        "id": 22,
        "name": "Neptun Suit",
        "type": "apartment",
        "price": 23,
        "capacity": 2,
        "image": "pictures/home-22.jpg",
        "location": "Varna",
        "booked": 531,
        "pets": true,
    },
    {
        "id": 23,
        "name": "Rose Home",
        "type": "apartment",
        "price": 76,
        "capacity": 4,
        "image": "pictures/home-23.jpg",
        "location": "Varna",
        "booked": 243,
        "pets": false,
    },
    {
        "id": 24,
        "name": "Fantasia Suit",
        "type": "apartment",
        "price": 34,
        "capacity": 2,
        "image": "pictures/home-24.jpg",
        "location": "Varna",
        "booked": 432,
        "pets": true,
    },
    {
        "id": 25,
        "name": "Water Apartment",
        "type": "apartment",
        "price": 98,
        "capacity": 4,
        "image": "pictures/home-25.jpg",
        "location": "Varna",
        "booked": 14,
        "pets": true,
    },
    {
        "id": 26,
        "name": "Mark's Favorite Apartment",
        "type": "apartment",
        "price": 23,
        "capacity": 2,
        "image": "pictures/home-26.jpg",
        "location": "Varna",
        "booked": 632,
        "pets": true,
    },
    {
        "id": 27,
        "name": "English Home",
        "type": "apartment",
        "price": 45,
        "capacity": 3,
        "image": "pictures/home-27.jpg",
        "location": "Varna",
        "booked": 123,
        "pets": true,
    },
    {
        "id": 28,
        "name": "Sea Suit",
        "type": "apartment",
        "price": 90,
        "capacity": 4,
        "image": "pictures/home-28.jpg",
        "location": "Varna",
        "booked": 91,
        "pets": true,
    },
    {
        "id": 29,
        "name": "Penthouse Sea View",
        "type": "apartment",
        "price": 200,
        "capacity": 4,
        "image": "pictures/home-29.jpg",
        "location": "Varna",
        "booked": 24,
        "pets": true,
    },
    {
        "id": 30,
        "name": "Vendetta Pethhouse",
        "type": "apartment",
        "price": 230,
        "capacity": 5,
        "image": "pictures/home-30.jpg",
        "location": "Varna",
        "booked": 543,
        "pets": false,
    },
    {
        "id": 31,
        "name": "Aloha Home",
        "type": "apartment",
        "price": 98,
        "capacity": 4,
        "image": "pictures/home-31.jpg",
        "location": "Sofia",
        "booked": 345,
        "pets": false,
    },
    {
        "id": 32,
        "name": "Georgeus Suit",
        "type": "apartment",
        "price": 23,
        "capacity": 3,
        "image": "pictures/home-32.jpg",
        "location": "Sofia",
        "booked": 19,
        "pets": true,
    },
    {
        "id": 33,
        "name": "Max's Favorite",
        "type": "apartment",
        "price": 45,
        "capacity": 2,
        "image": "pictures/home-33.jpg",
        "location": "Sofia",
        "booked": 111,
        "pets": false,
    },
    {
        "id": 34,
        "name": "Salvatore Suit",
        "type": "apartment",
        "price": 23,
        "capacity": 2,
        "image": "pictures/home-34.jpg",
        "location": "Sofia",
        "booked": 421,
        "pets": true,
    },
    {
        "id": 35,
        "name": "Orchard",
        "type": "apartment",
        "price": 76,
        "capacity": 3,
        "image": "pictures/home-35.jpg",
        "location": "Sofia",
        "booked": 23,
        "pets": true,
    },
    {
        "id": 36,
        "name": "The Cherries",
        "type": "apartment",
        "price": 87,
        "capacity": 3,
        "image": "pictures/home-36.jpg",
        "location": "Sofia",
        "booked": 921,
        "pets": false,
    },
    {
        "id": 37,
        "name": "The Cuckoo’s Nest",
        "type": "apartment",
        "price": 26,
        "capacity": 2,
        "image": "pictures/home-37.jpg",
        "location": "Sofia",
        "booked": 231,
        "pets": false,
    },
    {
        "id": 38,
        "name": "Millfield Lodge",
        "type": "apartment",
        "price": 56,
        "capacity": 3,
        "image": "pictures/home-38.jpg",
        "location": "Sofia",
        "booked": 241,
        "pets": true,
    },
    {
        "id": 39,
        "name": "Tythe Barn",
        "type": "apartment",
        "price": 87,
        "capacity": 2,
        "image": "pictures/home-39.jpg",
        "location": "Sofia",
        "booked": 1,
        "pets": true,
    },
    {
        "id": 40,
        "name": "Larkworthy",
        "type": "apartment",
        "price": 98,
        "capacity": 4,
        "image": "pictures/home-40.jpg",
        "location": "Sofia",
        "booked": 34,
        "pets": false,
    },
    {
        "id": 41,
        "name": "Peace apartment",
        "type": "apartment",
        "price": 76,
        "capacity": 3,
        "image": "pictures/home-41.jpg",
        "location": "Sofia",
        "booked": 92,
        "pets": true,
    },
    {
        "id": 42,
        "name": "MiniPalais",
        "type": "apartment",
        "price": 56,
        "capacity": 4,
        "image": "pictures/home-42.jpg",
        "location": "Sofia",
        "booked": 23,
        "pets": true,
    },
    {
        "id": 43,
        "name": "The Dorm Room",
        "type": "apartment",
        "price": 78,
        "capacity": 3,
        "image": "pictures/home-43.jpg",
        "location": "Sofia",
        "booked": 118,
        "pets": false,
    },
    {
        "id": 44,
        "name": "EcoStay",
        "type": "apartment",
        "price": 34,
        "capacity": 2,
        "image": "pictures/home-44.jpg",
        "location": "Sofia",
        "booked": 43,
        "pets": true,
    },
    {
        "id": 45,
        "name": "Shoebox",
        "type": "apartment",
        "price": 20,
        "capacity": 2,
        "image": "pictures/home-45.jpg",
        "location": "Sofia",
        "booked": 29,
        "pets": true,
    },
    {
        "id": 46,
        "name": "The Den",
        "type": "apartment",
        "price": 45,
        "capacity": 3,
        "image": "pictures/home-46.jpg",
        "location": "Sofia",
        "booked": 98,
        "pets": true,
    },
    {
        "id": 47,
        "name": "Wild Estates",
        "type": "apartment",
        "price": 50,
        "capacity": 4,
        "image": "pictures/home-47.jpg",
        "location": "Sofia",
        "booked": 24,
        "pets": false,
    },
    {
        "id": 48,
        "name": "Homes with peace",
        "type": "apartment",
        "price": 49,
        "capacity": 3,
        "image": "pictures/home-48.jpg",
        "location": "Sofia",
        "booked": 64,
        "pets": true,
    },
    {
        "id": 49,
        "name": "Jolly City",
        "type": "apartment",
        "price": 89,
        "capacity": 3,
        "image": "pictures/home-49.jpg",
        "location": "Sofia",
        "booked": 32,
        "pets": false,
    },
    {
        "id": 50,
        "name": "Joyous Home",
        "type": "apartment",
        "price": 95,
        "capacity": 4,
        "image": "pictures/home-50.jpg",
        "location": "Varna",
        "booked": 843,
        "pets": true,
    },
    {
        "id": 51,
        "name": "ApHEARTment",
        "type": "apartment",
        "price": 110,
        "capacity": 4,
        "image": "pictures/home-51.jpg",
        "location": "Varna",
        "booked": 100,
        "pets": false,
    },
    {
        "id": 52,
        "name": "Ideal Home",
        "type": "apartment",
        "price": 130,
        "capacity": 3,
        "image": "pictures/home-52.jpg",
        "location": "Varna",
        "booked": 395,
        "pets": true,
    },
    {
        "id": 53,
        "name": "The View",
        "type": "apartment",
        "price": 115,
        "capacity": 2,
        "image": "pictures/home-53.jpg",
        "location": "Varna",
        "booked": 195,
        "pets": true,
    },
    {
        "id": 54,
        "name": "Sunshine Place",
        "type": "apartment",
        "price": 120,
        "capacity": 3,
        "image": "pictures/home-54.jpg",
        "location": "Varna",
        "booked": 231,
        "pets": false,
    },
    {
        "id": 55,
        "name": "Sunny Place",
        "type": "apartment",
        "price": 110,
        "capacity": 3,
        "image": "pictures/home-55.jpg",
        "location": "Varna",
        "booked": 74,
        "pets": true,
    },
    {
        "id": 56,
        "name": "Artist’s Alley",
        "type": "apartment",
        "price": 120,
        "capacity": 4,
        "image": "pictures/home-56.jpg",
        "location": "Varna",
        "booked": 726,
        "pets": false,
    },
    {
        "id": 57,
        "name": "The Corner of Main",
        "type": "apartment",
        "price": 150,
        "capacity": 3,
        "image": "pictures/home-57.jpg",
        "location": "Varna",
        "booked": 396,
        "pets": false,
    },
    {
        "id": 58,
        "name": "East Side Living",
        "type": "apartment",
        "price": 200,
        "capacity": 6,
        "image": "pictures/home-58.jpg",
        "location": "Varna",
        "booked": 364,
        "pets": true,
    },
    {
        "id": 59,
        "name": "The Glass House",
        "type": "apartment",
        "price": 250,
        "capacity": 8,
        "image": "pictures/home-59.jpg",
        "location": "Varna",
        "booked": 974,
        "pets": false,
    },
    {
        "id": 60,
        "name": "View of the Sea",
        "type": "apartment",
        "price": 270,
        "capacity": 8,
        "image": "pictures/home-60.jpg",
        "location": "Varna",
        "booked": 356,
        "pets": true,
    },
    {
        "id": 61,
        "name": "Nature Home",
        "type": "cottage/cabin",
        "price": 150,
        "capacity": 4,
        "image": "pictures/home-61.jpg",
        "location": "Sofia",
        "booked": 942,
        "pets": false,
    },
    {
        "id": 62,
        "name": "Green Day",
        "type": "cottage/cabin",
        "price": 120,
        "capacity": 4,
        "image": "pictures/home-62.jpg",
        "location": "Sofia",
        "booked": 754,
        "pets": false,
    },
    {
        "id": 63,
        "name": "Silence Hill",
        "type": "cottage/cabin",
        "price": 100,
        "capacity": 4,
        "image": "pictures/home-63.jpg",
        "location": "Sofia",
        "booked": 246,
        "pets": false,
    },
    {
        "id": 64,
        "name": "Bird's Home",
        "type": "cottage/cabin",
        "price": 90,
        "capacity": 3,
        "image": "pictures/home-64.jpg",
        "location": "Sofia",
        "booked": 974,
        "pets": true,
    },
    {
        "id": 65,
        "name": "Take a Break",
        "type": "cottage/cabin",
        "price": 115,
        "capacity": 5,
        "image": "pictures/home-65.jpg",
        "location": "Sofia",
        "booked": 356,
        "pets": true,
    },
    {
        "id": 66,
        "name": "I was here",
        "type": "cottage/cabin",
        "price": 120,
        "capacity": 6,
        "image": "pictures/home-66.jpg",
        "location": "Sofia",
        "booked": 208,
        "pets": true,
    },
    {
        "id": 67,
        "name": "Green Valley",
        "type": "cottage/cabin",
        "price": 95,
        "capacity": 5,
        "image": "pictures/home-67.jpg",
        "location": "Sofia",
        "booked": 287,
        "pets": true,
    },
    {
        "id": 68,
        "name": "Sangria",
        "type": "cottage/cabin",
        "price": 110,
        "capacity": 5,
        "image": "pictures/home-68.jpg",
        "location": "Sofia",
        "booked": 97,
        "pets": true,
    },
    {
        "id": 69,
        "name": "Wood",
        "type": "cottage/cabin",
        "price": 150,
        "capacity": 5,
        "image": "pictures/home-69.jpg",
        "location": "Sofia",
        "booked": 46,
        "pets": true,
    },
    {
        "id": 70,
        "name": "Dark Green",
        "type": "cottage/cabin",
        "price": 112,
        "capacity": 6,
        "image": "pictures/home-70.jpg",
        "location": "Sofia",
        "booked": 75,
        "pets": true,
    },
    {
        "id": 71,
        "name": "I need space",
        "type": "cottage/cabin",
        "price": 134,
        "capacity": 6,
        "image": "pictures/home-71.jpg",
        "location": "Sofia",
        "booked": 35,
        "pets": true,
    },
    {
        "id": 72,
        "name": "Melania",
        "type": "cottage/cabin",
        "price": 90,
        "capacity": 4,
        "image": "pictures/home-72.jpg",
        "location": "Sofia",
        "booked": 94,
        "pets": true,
    },
    {
        "id": 73,
        "name": "Deeper",
        "type": "cottage/cabin",
        "price": 120,
        "capacity": 5,
        "image": "pictures/home-73.jpg",
        "location": "Sofia",
        "booked": 244,
        "pets": false,
    },
    {
        "id": 74,
        "name": "Social Club",
        "type": "cottage/cabin",
        "price": 180,
        "capacity": 7,
        "image": "pictures/home-74.jpg",
        "location": "Sofia",
        "booked": 34,
        "pets": false,
    },
    {
        "id": 75,
        "name": "Sleep",
        "type": "cottage/cabin",
        "price": 70,
        "capacity": 4,
        "image": "pictures/home-75.jpg",
        "location": "Sofia",
        "booked": 932,
        "pets": false,
    },
    {
        "id": 76,
        "name": "Pineview Lodge",
        "type": "cottage/cabin",
        "price": 112,
        "capacity": 4,
        "image": "pictures/home-76.jpg",
        "location": "Varna",
        "booked": 76,
        "pets": true,
    },
    {
        "id": 77,
        "name": "Moss Manor",
        "type": "cottage/cabin",
        "price": 130,
        "capacity": 4,
        "image": "pictures/home-77.jpg",
        "location": "Varna",
        "booked": 27,
        "pets": true,
    },
    {
        "id": 78,
        "name": "Moose Tracks Inn",
        "type": "cottage/cabin",
        "price": 99,
        "capacity": 5,
        "image": "pictures/home-78.jpg",
        "location": "Varna",
        "booked": 65,
        "pets": true,
    },
    {
        "id": 79,
        "name": "Lavender Haven",
        "type": "cottage/cabin",
        "price": 123,
        "capacity": 6,
        "image": "pictures/home-79.jpg",
        "location": "Varna",
        "booked": 23,
        "pets": true,
    },
    {
        "id": 80,
        "name": "Crested View",
        "type": "cottage/cabin",
        "price": 200,
        "capacity": 4,
        "image": "pictures/home-80.jpg",
        "location": "Varna",
        "booked": 403,
        "pets": true,
    },
    {
        "id": 81,
        "name": "Hollyhock House",
        "type": "cottage/cabin",
        "price": 150,
        "capacity": 5,
        "image": "pictures/home-81.jpg",
        "location": "Varna",
        "booked": 493,
        "pets": false,
    },
    {
        "id": 82,
        "name": "The Hideaway",
        "type": "cottage/cabin",
        "price": 120,
        "capacity": 5,
        "image": "pictures/home-82.jpg",
        "location": "Varna",
        "booked": 322,
        "pets": false,
    },
    {
        "id": 83,
        "name": "Moonlight Trail",
        "type": "cottage/cabin",
        "price": 97,
        "capacity": 3,
        "image": "pictures/home-83.jpg",
        "location": "Varna",
        "booked": 70,
        "pets": false,
    },
    {
        "id": 84,
        "name": "Eagle Run",
        "type": "cottage/cabin",
        "price": 126,
        "capacity": 4,
        "image": "pictures/home-84.jpg",
        "location": "Varna",
        "booked": 229,
        "pets": true,
    },
    {
        "id": 85,
        "name": "The Whiskey Way Inn ",
        "type": "cottage/cabin",
        "price": 87,
        "capacity": 3,
        "image": "pictures/home-85.jpg",
        "location": "Varna",
        "booked": 549,
        "pets": true,
    },
    {
        "id": 86,
        "name": "Deerfield Bottom",
        "type": "cottage/cabin",
        "price": 145,
        "capacity": 5,
        "image": "pictures/home-86.jpg",
        "location": "Varna",
        "booked": 493,
        "pets": true,
    },
    {
        "id": 87,
        "name": "Salt Water Way",
        "type": "cottage/cabin",
        "price": 105,
        "capacity": 4,
        "image": "pictures/home-87.jpg",
        "location": "Varna",
        "booked": 22,
        "pets": true,
    },
    {
        "id": 88,
        "name": "The Wayfarer",
        "type": "cottage/cabin",
        "price": 122,
        "capacity": 4,
        "image": "pictures/home-88.jpg",
        "location": "Varna",
        "booked": 483,
        "pets": false,
    },
    {
        "id": 89,
        "name": "Gray Whale Watch",
        "type": "cottage/cabin",
        "price": 78,
        "capacity": 4,
        "image": "pictures/home-89.jpg",
        "location": "Varna",
        "booked": 93,
        "pets": true,
    },
    {
        "id": 90,
        "name": "Hawk Hideout",
        "type": "cottage/cabin",
        "price": 165,
        "capacity": 4,
        "image": "pictures/home-90.jpg",
        "location": "Varna",
        "booked": 234,
        "pets": true,
    },
    {
        "id": 91,
        "name": "Tree Hause",
        "type": "unique",
        "price": 300,
        "capacity": 4,
        "image": "pictures/home-91.jpg",
        "location": "Sofia",
        "booked": 932,
        "pets": false,
    },
    {
        "id": 92,
        "name": "Sea Adventure",
        "type": "unique",
        "price": 350,
        "capacity": 5,
        "image": "pictures/home-92.jpg",
        "location": "Varna",
        "booked": 494,
        "pets": false,
    },
    {
        "id": 93,
        "name": "Under stars",
        "type": "unique",
        "price": 290,
        "capacity": 5,
        "image": "pictures/home-93.jpg",
        "location": "Sofia",
        "booked": 643,
        "pets": false,
    },
    {
        "id": 94,
        "name": "Animal Home",
        "type": "unique",
        "price": 310,
        "capacity": 3,
        "image": "pictures/home-94.jpg",
        "location": "Sofia",
        "booked": 564,
        "pets": true,
    },
    {
        "id": 95,
        "name": "Train suit",
        "type": "unique",
        "price": 150,
        "capacity": 2,
        "image": "pictures/home-95.jpg",
        "location": "Sofia",
        "booked": 244,
        "pets": true,
    },
    {
        "id": 96,
        "name": "Not a casual room",
        "type": "unique",
        "price": 180,
        "capacity": 2,
        "image": "pictures/home-96.jpg",
        "location": "Sofia",
        "booked": 2231,
        "pets": true,
    },
    {
        "id": 97,
        "name": "Blue Lagoon",
        "type": "unique",
        "price": 200,
        "capacity": 2,
        "image": "pictures/home-97.jpg",
        "location": "Varna",
        "booked": 121,
        "pets": true,
    },
    {
        "id": 98,
        "name": "Versace",
        "type": "unique",
        "price": 350,
        "capacity": 2,
        "image": "pictures/home-98.jpg",
        "location": "Varna",
        "booked": 224,
        "pets": true,
    },
    {
        "id": 99,
        "name": "Indian Hill",
        "type": "unique",
        "price": 200,
        "capacity": 2,
        "image": "pictures/home-99.jpg",
        "location": "Varna",
        "booked": 3335,
        "pets": false,
    },
    {
        "id": 100,
        "name": "Look at the stars",
        "type": "unique",
        "price": 450,
        "capacity": 2,
        "image": "pictures/home-100.jpg",
        "location": "Varna",
        "booked": 54,
        "pets": false,
    },
];