myObjects = [
  {
    picture: "pictures/Sangaria.jpg",
    rating: 4.95,
    title: "Sangaria and Secrets with Drag Taste",
    visitedTimes: 5545,
    location: "Portugal",
    price: 69,
    category: "Entertainment",
    id: 1,
  },
  {
    picture: "pictures/PlagueDoctor.jpg",
    rating: 4.97,
    title: "Follow a Plague Doctor Through Prague",
    visitedTimes: 2175,
    location: "Czech Republic",
    price: 31,
    category: "Entertainment",
    id: 2,
  },
  {
    picture: "pictures/Historical.jpg",
    rating: 4.95,
    title: "'True vs False' Funny Historical Game",
    visitedTimes: 2175,
    location: "Greece",
    price: 32,
    category: "History & Culture",
    id: 3,
  },
  {
    picture: "pictures/Scavenger.jpeg",
    rating: 4.91,
    title: "Living Room Legends Scavenger Hunt Game",
    visitedTimes: 1288,
    location: "United States",
    price: 18,
    category: "Entertainment",
    id: 2,
  },
  {
    picture: "pictures/fabGame.jpg",
    rating: 4.95,
    title: "'no Spain no Game' The Fabulous Game !",
    visitedTimes: 2175,
    location: "Mexico",
    price: 22,
    category: "Great for Groups",
    id: 4,
  },
  {
    picture: "pictures/Mexican Tacos.jpg",
    rating: 4.98,
    title: "Make Mexican Street Tacos with a Pro Chef",
    visitedTimes: 823,
    location: "Mexico",
    price: 32,
    category: "Cooking",
    id: 5,
  },
  {
    picture: "pictures/Love.jpg",
    rating: 4.96,
    title: "Love and Secrets with Drag Taste",
    visitedTimes: 1235,
    location: "Portugal",
    price: 59,
    category: "Entertainment",
    id: 6,
  },
  {
    picture: "pictures/Magic.jpeg",
    rating: 4.98,
    title: "Harry Poter Magic in Edinburgh Tour",
    visitedTimes: 2175,
    location: "United Kingdom",
    price: 25,
    category: "Magic",
    id: 7,
  },
  {
    picture: "pictures/Pasta.jpg",
    rating: 4.94,
    title: "Pasta with the Grandmas",
    visitedTimes: 1872,
    location: "Italy",
    price: 69,
    category: "Cooking",
    id: 8,
  },
  {
    picture: "pictures/lama.jpg",
    rating: 4.98,
    title: "Meet and Draw a llama",
    visitedTimes: 206,
    location: "Australia",
    price: 49,
    category: "Great for Groups",
    id: 9,
  },
  {
    picture: "pictures/RedWine.jpeg",
    rating: 4.95,
    title: "How to Paint with Red Wine",
    visitedTimes: 982,
    location: "Spain",
    price: 24,
    category: "Great for Groups",
    id: 10,
  },
  {
    picture: "pictures/sushi.jpeg",
    rating: 4.99,
    title: "Make Tokiyo Sushi Roll at Home with a Pro",
    visitedTimes: 1372,
    location: "Japan",
    price: 43,
    category: "Cooking",
    id: 11,
  },
  {
    picture: "pictures/magicTrick.jpeg",
    rating: 4.99,
    title: "Bring Magic Home",
    visitedTimes: 99,
    location: "Canada",
    price: 31,
    category: "Magic",
    id: 12,
  },
  {
    picture: "pictures/Cofee.jpg",
    rating: 4.98,
    title: "Worlds Top Coffee Masterclass",
    visitedTimes: 2256,
    location: "Mexico",
    price: 18,
    category: "Great for Groups",
    id: 13,
  },
  {
    picture: "pictures/oldMan.jpg",
    rating: 4.97,
    title: "Irish Village,History,Culture & Craic",
    visitedTimes: 1288,
    location: "Ireland",
    price: 28,
    category: "History & Culture",
    id: 14,
  },
  {
    picture: "pictures/Monk.jpeg",
    rating: 4.91,
    title: "Healing Concert Cellist & Japanese Monk",
    visitedTimes: 911,
    location: "Japan",
    price: 8,
    category: "History & Culture",
    id: 15,
  },
  {
    picture: "pictures/franceWoman.jpg",
    rating: 4.92,
    title: "A fabulous day in Paris with a Parisian",
    visitedTimes: 1221,
    location: "France",
    price: 32,
    category: "Arts & Writing",
    id: 16,
  },
  {
    picture: "pictures/chef.jpg",
    rating: 4.95,
    title: "Make Gnocchi Ravioli at Home",
    visitedTimes: 56,
    location: "Italy",
    price: 41,
    category: "Cooking",
    id: 17,
  },
  {
    picture: "pictures/greenMan.jpeg",
    rating: 4.99,
    title: "Cardio Dance with Drag Choreographer",
    visitedTimes: 77,
    location: "United States",
    price: 25,
    category: "Dance",
    id: 18,
  },
];
